[package]
name = "alar"
version = "1.1.0"
authors = ["malachma <malachma@microsoft.com>", "pagienge <pagienge@microsoft.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-mount = "3.*"
fs_extra = "1.3.0"
clap = { version = "3.*", features = ["cargo"] }
reqwest = { version = "0.12", features = ["blocking"] }
serde_json = "1.0.120"
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
anyhow = "1.0.*"
env_logger = "0.11.*"
log = "0.4.*"
simple-base64 = "0.*"
